[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '127.0.0.1'
port = 3002

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001


####################################################### END OF GLOBAL CONFIGURATION #######################################################

[[chains]]
id = 'sourcechain-testnet'
rpc_addr = 'https://testnet.sourceprotocol.io:26657'
grpc_addr = 'https://testnet.sourceprotocol.io:9090'
websocket_addr = 'wss://testnet.sourceprotocol.io:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'source'
key_name = 'mysourceaccount'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 0.001, denom = 'usource' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-62'], # osmos
  ['transfer', 'channel-63'], # cosmos
  ['transfer', 'channel-64'], # juno
]

[[chains]]
id = 'osmo-test-4'
rpc_addr = 'https://testnet-rpc.osmosis.zone:443'
grpc_addr = 'http://grpc-test.osmosis.zone:9090'
websocket_addr = 'wss://testnet-rpc.osmosis.zone:443/websocket'
rpc_timeout = '10s'
account_prefix = 'osmo'
key_name = 'myosmoaccount'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.001, denom = 'uosmo' }
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 150000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '9days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-389']
]

[[chains]]
id = 'theta-testnet-001'
rpc_addr = 'https://rpc.state-sync-01.theta-testnet.polypore.xyz:443'
grpc_addr = 'http://grpc.state-sync-01.theta-testnet.polypore.xyz:9090'
websocket_addr = 'wss://rpc.state-sync-01.theta-testnet.polypore.xyz:443/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'mycosmosaccount'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.001, denom = 'uatom' }
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 150000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-552'],
]

[[chains]]
id = 'uni-3'
rpc_addr = 'https://rpc.uni.junonetwork.io:443'
grpc_addr = 'https://grpc.juno.giansalex.dev:443'
websocket_addr = 'wss://rpc.uni.juno.deuslabs.fi:443/websocket'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'myjunoaccount'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 0.001, denom = 'ujunox' }
gas_multiplier = 2
max_msg_num = 30
max_tx_size = 150000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', "channel-176"],
]