[global]

log_level = 'info'

[mode]

[mode.clients]

enabled = true
refresh = true
misbehaviour = true

[mode.connections]

enabled = true

[mode.channels]

enabled = true

[mode.packets]

enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]

enabled = true
host = '127.0.0.1'
port = 3000

[telemetry]

enabled = true
host = '127.0.0.1'
port = 3001


####################################################### END OF GLOBAL CONFIGURATION #######################################################

[[chains]]

# "chainId": "uni-2",
# "chainName": "Juno Uni Testnet",
# "rpc": "https://rpc.uni.juno.deuslabs.fi:443/",
# "rest": "https://lcd.uni.juno.deuslabs.fi:443/",
# - https://rpc.uni.junonetwork.io/
# - https://api.uni.junonetwork.io/
# - https://rpc.uni.juno.deuslabs.fi/
# - https://lcd.uni.juno.deuslabs.fi/
# - https://faucet.uni.juno.deuslabs.fi/ 
# - https://rpc.uni.junomint.com:443/ 
# - https://api.uni.junomint.com:443/
# - https://uni-api.blockpane.com/ # RPC and LCD
#   "address": "35.243.205.230:9090",
#           "provider": "strangelove"
#         {
# "address": "grpc-juno-ia.notional.ventures:443",
# "provider": "Notional"

id = 'uni-3'
rpc_addr = 'https://rpc.uni.junonetwork.io:443'
grpc_addr = 'https://grpc.juno.giansalex.dev:443'
#grpc_addr = 'https://grpc-juno-ia.notional.ventures:443'
websocket_addr = 'wss://rpc.uni.juno.deuslabs.fi:443/websocket'
rpc_timeout = '10s'
account_prefix = 'juno'
key_name = 'pj4'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 0.001, denom = 'ujunox' }
gas_adjustment = 1.0
max_msg_num = 30
max_tx_size = 150000
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '1days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = ''
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-14'],
]

[[chains]]
id = 'sourcechain-testnet'
rpc_addr = 'https://testnet.sourceprotocol.io:26657'
grpc_addr = 'https://testnet.sourceprotocol.io:9090'
websocket_addr = 'ws://testnet.sourceprotocol.io:26658/websocket'
rpc_timeout = '10s'
account_prefix = 'source'
key_name = 'ps1'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 700000
gas_price = { price = 0.001, denom = 'usource' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '30s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
# address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-18'],
]