---
on:
  push:
    paths:
      - '**.go'      
      - 'go.sum'
  pull_request:
    paths:
      - '**.go'
      - 'go.sum'
name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
      - run: go build ./...

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test ./...

  tidy:
    runs-on: ubuntu-latest
    name: tidy
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0
      - run: |
          go mod tidy
          CHANGES_IN_REPO=$(git status --porcelain)
          if [[ -n "$CHANGES_IN_REPO" ]]; then
            echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
            git status && git --no-pager diff
            exit 1
          fi
