name: Gov Contract CI - Submit Contract Prop

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose
        run: STAKE_TOKEN="usource" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'Source-Protocol-Cosmos/cw-unity-prop'
          ref: 'v0.3.2'
      - name: Test smart contract gov prop
        run: |
          chmod a+x ./scripts/submit_gov_ci.sh
          ./scripts/submit_gov_ci.sh source1z2pwal23rn7acdluxmj9345g2ndr9rsw4ukhyr
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

