name: Contract CI

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose
        run: STAKE_TOKEN="usource" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'envoylabs/whoami'
          ref: 'v0.5.6'
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

