---
name: Contract CI

on:
  pull_request:
    paths:
    - '**.go'
  push:
    paths:
    - '**.go'
    tags:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose
        run: STAKE_TOKEN="usourcex" TIMEOUT_COMMIT=500ms docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'envoylabs/whoami'
          ref: 'v0.7.1-alpha'
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

