name: release binary

on:
  release:
    types: [created]

jobs:
  release-alpine-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker compose
        run: STAKE_TOKEN="usource" docker-compose up -d
      - name: Copy binary
        run: docker cp source_node_1:/usr/bin/sourced ./sourced
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./sourced
          asset_name: sourced
          asset_content_type: application/octet-stream
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
